/*
* Copyright (c) 2008-2010, Helios (helios.vmg@gmail.com)
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*     * Redistributions of source code must retain the above copyright notice,
*       this list of conditions and the following disclaimer.
*     * Redistributions in binary form must reproduce the above copyright
*       notice, this list of conditions and the following disclaimer in the
*       documentation and/or other materials provided with the distribution.
*     * The name of the author may not be used to endorse or promote products
*       derived from this software without specific prior written permission.
*     * Products derived from this software may not be called "ONSlaught" nor
*       may "ONSlaught" appear in their names without specific prior written
*       permission from the author.
*
* THIS SOFTWARE IS PROVIDED BY HELIOS "AS IS" AND ANY EXPRESS OR IMPLIED
* WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
* EVENT SHALL HELIOS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
* OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef NONS_COMMON_H
#define NONS_COMMON_H
typedef unsigned long ulong;
typedef unsigned short ushort;
typedef unsigned char uchar;

#define NONS_SYS_WINDOWS (defined _WIN32 || defined _WIN64)
#define NONS_SYS_LINUX (defined linux || defined __linux)
#define NONS_SYS_BSD (defined __bsdi__)
#define NONS_SYS_UNIX (defined __unix__ || defined __unix)

#if NONS_SYS_WINDOWS
typedef void *HANDLE;
#ifndef _USRDLL
#define DLLexport __declspec(dllexport)
#else
#define DLLexport __declspec(dllimport)
#endif

#ifndef _WIN64
typedef ulong DWORD;
#else
typedef ushort DWORD;
#endif
#else
#define DLLexport
#endif

#ifdef _MSC_VER
#define NONS_COMPILER_VCPP
#pragma warning(disable:4065) //no "switch statement contains 'default' but no 'case' labels", generated by Bison.
#pragma warning(disable:4996) //no "unsafe" functions
#endif

#include <cwchar>
#ifndef WCHAR_MAX
#error "WCHAR_MAX is not defined."
#endif
#if WCHAR_MAX<0xFFFF
#error "Wide characters on this implementation are too narrow."
#endif

#include <climits>
#if ULONG_MAX<0xFFFFFFFF
#error "longs on this implementation are too small."
#endif

extern const int rmask;
extern const int gmask;
extern const int bmask;
extern const int amask;
extern const int rshift;
extern const int gshift;
extern const int bshift;
extern const int ashift;
extern int lastClickX;
extern int lastClickY;
extern DLLexport ulong cpu_count;

extern DLLexport volatile bool ctrlIsPressed;
extern DLLexport volatile bool forceSkip;

#define CURRENTLYSKIPPING (ctrlIsPressed || forceSkip)
#endif
